version: '3.8'
services:
  salon-app:
    container_name: kubernetes-app-v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: '.'
      args:
        uid: ${UID}
        APACHE_SERVER_NAME: "local.kubernetes.com"
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_LOG_DIR=
      - DB_CONNECTION=mysql
      - DB_HOST="host.docker.internal"
      - DB_PORT=3306
      - DB_DATABASE=kubernet
      - DB_USERNAME=vfc
      - DB_PASSWORD=Hrhk@4321@!!
      - QUEUE_CONNECTION=database
