# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: SHJoa0A0MzIxODghIQ==
  mysql-user: a3ViZVVzZXI=
  mysql-password: SHJoa0A0MzIxODhAIw==
  mysql-database: a3ViZV9kZW1vX2xhcmF2ZWw=
